routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware('auth')->group(function() {
    Route::get('/', [ArticleController::class, 'index']);
    Route::resource('articles', ArticleController::class);
    Route::resource('comments', CommentController::class)->only('store', 'destroy')->middleware('auth');
    Route::get('articles/publish/{article}', [ArticleController::class, 'article_grant'])->name('article.grant');
    Route::put('articles/permit/{article}', [ArticleController::class, 'article_permit'])->name('article.permit');
    Route::get('/users/{user_id}', [UsersController::class, 'profile'])->name('profiles');
    Route::put('/allow-comment/{comment}', [CommentController::class, 'allow_comment'])->name('allow-comment');
    Route::post('/articles/{article}/rate', [ArticleController::class, 'rate_article'])->name('rate.article');
});


Auth::routes();

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'body', 'article_category_id', 'tag_id', 'user_id', 'published_at'];

    public function article_category() {
        return $this->belongsTo(ArticleCategory::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function tag() {
        return $this->belongsTo(Tag::class);
    }

    public function qualities() {
        return $this->hasMany(Quality::class);
    }

    public function relevances() {
        return $this->hasMany(Relevance::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\ArticleCategory;
use App\Models\Comment;
use App\Models\Quality;
use App\Models\Relevance;
use App\Models\Satisfaction;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $articles = Article::paginate(6);
        return view('Articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $article_categories = ArticleCategory::all();
        $tags = Tag::all();
        return view('Articles.create', compact('article_categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request['user_id'] = Auth::user()->id;
        $validated = $request->validate([
            'title' => 'required',
            'body' => 'required',
            'user_id' => 'required',
            'article_category_id' => 'required',
            'tag_id' => 'required',
            'published_at' => 'nullable'
        ]);
        $article = new Article($validated);
        $article->save();
        return redirect()->route('articles.index')->with('success', 'Article created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(Article $article)
    {
        $comments = Comment::all()->where('article_id', $article->id);
        return view('Articles.show', compact('article', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Article $article)
    {
        $tags = Tag::all();
        $article_categories = ArticleCategory::all();
        return view('Articles.edit', compact('article', 'tags', 'article_categories'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Article $article)
    {
        $request['user_id'] = Auth::user()->id;
        $validated = $request->validate([
            'title' => 'required',
            'body' => 'required',
            'published_at' => 'nullable',
            'tag_id' => 'required',
            'article_category_id' => 'required',
            'user_id' => 'required'
        ]);

        $article->update($validated);

        return redirect()->route('articles.index')->with('success', 'Article updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->back()->with('success', 'Article deleted successfully');
    }
    public function article_grant($article) {
        return view('Articles.grant', compact('article'));
    }

    public function article_permit(Request $request, Article $article) {
        $validated = $request->validate([
            'published_at' => 'required'
        ]);
        $article->published_at = $validated['published_at'];
        $article->save();
        return redirect()->back()->with('success', 'Published date is ' . $article->published_at);
    }

    public function rate_article(Request $request, Article $article) {
        $validated = $request->validate([
           'quality' => 'nullable',
            'relevance' => 'nullable',
            'satisfied' => 'nullable'
        ]);
        if ($validated["quality"] != null){
            $quality = new Quality([
                'quality' => $validated['quality'],
                'user_id' => $request->user()->id,
                'article_id' => $article->id]);
            $quality->save();
        }
        if ($validated['relevance'] != null) {
            $relevance = new Relevance([
                'relevance' => $validated['relevance'],
                'user_id' => $request->user()->id,
                'article_id' => $article->id]);
            $relevance->save();
        }
        if (isset($validated["satisfied"]) && $validated["satisfied"] != null){
            $satisfaction = new Satisfaction([
                'satisfied' => $validated['satisfied'],
                'user_id' => $request->user()->id,
                'article_id' => $article->id]);
            $satisfaction->save();
        }
        return redirect()->back()->with('Success');
    }
}

resources/views/Articles/create.blade.php
@extends('layouts.app')
@section('content')
    <div>
        @include('notifications.alerts')
        <form action="{{route('articles.store')}}" method="post">
            @csrf

            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                <input type="text" class="form-control" id="title" name="title" value="{{old('title')}}">
            </div>

            <div class="mb-3">
                <label for="body" class="form-label">Body</label>
                <input type="text" class="form-control" id="body" name="body" value="{{old('body')}}">
            </div>

            @can('is-admin')
                <div class="mb-3">
                    <label for="published_at" class="form-label">Date published</label>
                    <input type="date" class="form-control" id="published_at" name="published_at" value="{{old('published_at')}}">
                </div>
            @endcan

            <div class="mb-3">
                <label for="tag" class="form-label">Tag</label>
                <select class="form-select" name="tag_id" id="tag">
                    <option selected value="{{null}}">Choose a tag</option>
                    @foreach($tags as $tag)
                        <option value="{{$tag->id}}" @if(old('tag_id')==$tag->id) selected @endif>{{$tag->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-3">
                <label for="category" class="form-label">Article Category</label>
                <select class="form-select" name="article_category_id" id="category">
                    <option selected value="{{null}}">Choose an article category</option>
                    @foreach($article_categories as $category)
                        <option value="{{$category->id}}" @if(old('article_category_id')==$category->id) selected @endif>{{$category->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/Articles/edit.blade.php
@extends('layouts.app')
@section('content')
    <div>
        @include('notifications.alerts')
        <form action="{{route('articles.update', ['article' => $article])}}" method="post">

            @csrf
            @method('PUT')

            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                <input type="text" class="form-control" id="title" name="title" value="{{old('title') ?: $article->title}}">
            </div>

            <div class="mb-3">
                <label for="body" class="form-label">Body</label>
                <input type="text" class="form-control" id="body" name="body" value="{{old('body') ?: $article->body}}">
            </div>

            @can('is-admin')
                <div class="mb-3">
                    <label for="published_at" class="form-label">Date published</label>
                    <input type="date" class="form-control" id="published_at" name="published_at" value="{{old('published_at') ?: $article->published_at}}">
                </div>
            @endcan

            <div class="mb-3">
                <label for="tag" class="form-label">Tag</label>
                <select class="form-select" name="tag_id" id="tag">
                    <option selected value="{{null}}">Choose a tag</option>
                    @foreach($tags as $tag)
                        <option value="{{$tag->id}}"
                                @if(old('tag_id')==$tag->id || $article->tag->id == $tag->id) selected @endif
                        >{{$tag->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-3">
                <label for="category" class="form-label">Article Category</label>
                <select class="form-select" name="article_category_id" id="category">
                    <option selected value="{{null}}">Choose an article category</option>
                    @foreach($article_categories as $category)
                        <option value="{{$category->id}}"
                                @if(old('article_category_id')==$category->id || $article->article_category->id == $category->id) selected @endif
                        >{{$category->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/Articles/grant.blade.php
@extends('layouts.app')
@section('content')
    <form action="{{route('article.permit', ['article' => $article])}}" method="post">
        @include('notifications.alerts')
        @csrf
        @method('PUT')
        <div class="mb-3">
            <label for="published_at">Publish At</label>
            <input type="date" class="form-control" name="published_at" id="published_at">
        </div>
        <div class="mb-3">
            <input type="submit" class="btn btn-warning">
        </div>
    </form>
@endsection

resources/views/Articles/index.blade.php
@extends('layouts.app')

@section('content')
    @include('notifications.alerts')
    <div>
        <a href="{{route('articles.create')}}" class="btn btn-primary my-3 btn-lg">Add an article</a>
    </div>
    <table class="text-center">
        <thead>
            <tr>
                <td colspan="7">All Articles</td>
            </tr>
            <tr>
                <td >Title</td>
                <td>Category</td>
                <td>Quality</td>
                <td>Relevance</td>
                <td>Author</td>
                <td>Date Published</td>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            @foreach($articles as $article)
                @if($article->published_at != null)
                    @include('Articles.index_view')
                @endif
            @endforeach
        </tbody>
    </table>


    <div class="justify-content-md-center p-5">
        <div class="col-md-auto">
            {{ $articles->links() }}
        </div>
    </div>

@endsection

resources/views/Articles/index_view.blade.php
<tr>
    <td>
        <a href="{{route('articles.show', ['article' => $article])}}">
            <h3 class="card-title py-4">{{$article->title}}</h3>
        </a>
    </td>

    <td>
        <p>{{$article->article_category->name}}</p>
    </td>

    <td>
        {{display_quality($article)}}
    </td>

    <td>
        {{display_relevance($article)}}
    </td>

    <td>
        <a href="{{route('profiles', ['user_id'=>$article->user->id])}}">{{$article->user->name}}</a>
    </td>

    <td>
        {{$article->published_at}}
    </td>

    <td>
        @can('update-article', $article)
            <a href="{{route('articles.edit', ['article' => $article])}}" class="btn btn-outline-warning my-3">Edit</a>
        @endcan
        @can('delete-article', $article)
            <form action="{{route('articles.destroy', ['article' => $article])}}" method="post">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-outline-danger">Delete</button>
            </form>
        @endcan
    </td>
</tr>

resources/views/Articles/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="my-4">
        <h1>{{$article->title}}<span class="border border-3 bg-warning d-inline-block mx-4">{{$article->tag->name}}</span></h1>
        <p><b>Author: </b><a href="{{route('profiles', ['user_id'=>$article->user->id])}}">{{$article->user->name}}</a></p>
        <p><b>Quality: </b>{{display_quality($article)}}</p>
        <p><b>Relevance: </b>{{display_relevance($article)}}</p>
        <p><b>Satisfied users number: </b>{{display_satisfaction($article)}}</p>
        <p><b>Created at: </b>{{$article->created_at}}</p>
        <p><b>Published at: </b>{{$article->published_at}}</p>
        @can('is-admin', $article)
            <a href="{{route('article.grant', ['article' => $article])}}" class="btn btn-warning">Publishing date</a>
        @endcan
        <p class="my-5">{{$article->body}}</p>
    </div>
    <div class="row comments my-5">
        <div class="col-6">
            <form action="{{route('rate.article', ['article' => $article])}}" method="post">
                @csrf
                @method('POST')
                <div class="row">
                    <div class="col-4">
                        <select name="quality" class="form-select">
                            <option value="{{null}}">Select a quality mark</option>
                            @for($i=-5; $i<=5; $i++)
                                <option value="{{$i}}">{{$i}}</option>
                            @endfor
                        </select>
                    </div>
                    <div class="col-4">
                        <select name="relevance" class="form-select">
                            <option value="{{null}}">Select a relevance mark</option>
                            @for($i=-5; $i<=5; $i++)
                                <option value="{{$i}}">{{$i}}</option>
                            @endfor
                        </select>
                    </div>
                    <div class="col-4">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="satisfied" value="1" name="satisfied">
                            <label class="form-check-label" for="satisfied">
                                Satisfied
                            </label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info my-4">Submit</button>
                </div>
            </form>
        </div>

        <div class="col-6">
            <div class="border border-1 p-4">
                @include('notifications.alerts')
                <form action="{{route('comments.store')}}" method="post">
                    @csrf
                    @method("POST")
                    <input type="hidden" value="{{$article->id}}" name="article_id">
                    <div class="mb-3">
                        <label for="body" class="form-label">Leave a comment</label>
                        <input type="text" class="form-control" id="body" name="body">
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-outline-info btn-lg">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="">
        @foreach($comments as $comment)
            @if($comment->is_allowed || is_admin())
                <div class="p-3 border border-1">
                    <p>{{$comment->user->name}} commented at {{$comment->created_at}}</p>
                    <p>{{$comment->body}}</p>
                    @can('delete-comment', $comment)
                        <form action="{{route('comments.destroy', ['comment' => $comment])}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </form>
                    @endcan
                    @if(!$comment->is_allowed)
                        @can('is-admin')
                            <form action="{{route('allow-comment', ['comment' => $comment])}}" method="post">
                                @csrf
                                @method('PUT')
                                <button type="submit" class="btn btn-warning">Allow</button>
                            </form>
                        @endcan
                    @endif
                </div>
            @endif
        @endforeach
    </div>
@endsection